### ISSUE TITLE
Interpolation not being highlighted

### ISSUE THREAD

**Issue by VitorAlaluf** [tobiasalthoff/vscode-atom-material-theme#19] opened 2023-01-16 17:00 UTC
I've been using material-theme for a long time now, mainly for coding in JS, the only problem is that, when using interpolation such as:

![image](https://user-images.githubusercontent.com/51958276/212731265-582bb06d-3598-4089-ba3e-07830342fb1a.png)

the theme doesn't highlight the string, often leading to confusion or unnecessary double-checks. 
Is there an solution I'm not aware of?

**Comment by tobiasalthoff** [comment] 2023-02-25 19:33
Hey @VitorAlaluf ,
I've tested it with Language set to "JavaScript" (in the bottom right of vscode) and it looks fine:

<img width="1019" alt="Screenshot 2023-02-25 at 20 32 22" src="https://user-images.githubusercontent.com/17332438/221376098-a0fe993f-7bea-42d0-89c8-34dcc820324b.png">

Which language is set in your example?

**Comment by tobiasalthoff** [comment] 2023-03-07 10:56
Hey @VitorAlaluf ,
I'll close this issue as I can't reproduce it. Feel free to reopen this issue :-)

**Closed as not planned by tobiasalthoff** 2023-03-07 10:56 UTC
