### ISSUE TITLE
Syntax highlighting for Dockerfile not working after installing Atom Material Theme

### ISSUE THREAD

**Issue by tebaly** [tobiasalthoff/vscode-atom-material-theme#21] opened 2023-04-19 11:55 UTC
I have recently installed the Atom Material Theme extension in Visual Studio Code, but I have noticed that the syntax highlighting for Dockerfile is not working anymore. Before installing the extension, the syntax highlighting was working fine, and I believe it was supported by the built-in Docker extension. However, after installing Atom Material Theme, the syntax highlighting for Dockerfile is no longer working.

# Steps to Reproduce:

Install the Atom Material Theme extension in Visual Studio Code.
Open a Dockerfile or create a new one.
Notice that syntax highlighting is not working.
Expected Behavior:

The syntax highlighting for Dockerfile should work with both the built-in Docker extension and the Atom Material Theme extension.

# Actual Behavior:

The syntax highlighting for Dockerfile is not working after installing the Atom Material Theme extension. It seems like there is a conflict between the theme and the Docker extension, and the theme is overriding the syntax highlighting provided by the extension.

## Environment:

Operating System: Ubuntu 22
Visual Studio Code version: 1.77
Atom Material Theme extension version: 1.10.9
Docker extension version: 1.25

## Additional Information:

I have tried disabling other extensions, but the issue persists. Also, I have tried using other themes, and the syntax highlighting for Dockerfile works with those themes. Therefore, I believe the issue is caused by the Atom Material Theme extension.

**Comment by tobiasalthoff** [comment] 2023-04-20 12:50
Hey @tebaly ,
I've tested the theme with a dockerfile and the syntax highlighting looks good. What does "Language Mode" say at the bottom right? "Docker" or "Dockerfile"?

**Comment by tebaly** [comment] 2023-04-20 22:13
Thank you for your response. I have double-checked the language mode, and it is set to "Dockerfile". Also, I have disabled all other extensions except for the "Docker" extension, which comes pre-installed with Visual Studio Code, and the "Atom Material Theme" extension. However, the syntax highlighting for Dockerfile is still not working with the Atom Material Theme extension installed. I would appreciate any further guidance on how to resolve this issue. Thank you.

**Comment by tebaly** [comment] 2023-04-20 22:17
I would like to try running a virtual machine and installing the Atom Material Theme extension on it to see if the issue persists. 
Also, just to clarify, I am currently running Ubuntu and I installed Visual Studio Code using the snap package manager.

**Comment by tebaly** [comment] 2023-04-20 22:57
I have set up a virtual machine and installed Visual Studio Code along with the Docker extension and the Atom Material Theme extension.

After testing, I found that the syntax highlighting for Dockerfile worked perfectly fine until I installed the Atom Material Theme extension. Once I installed it, the syntax highlighting stopped working for Dockerfile even on the virtual machine.

This seems to indicate that the issue is specifically related to the Atom Material Theme extension and not any other factors like conflicting extensions or dependencies.

Thank you for your help in troubleshooting this issue.

![Screenshot_ubuntu20 04_2023-04-21_02:43:31](https://user-images.githubusercontent.com/9466814/233502809-8fd1e470-fda8-48e5-bb39-488251926795.png)
![Screenshot_ubuntu20 04_2023-04-21_02:42:38](https://user-images.githubusercontent.com/9466814/233502816-106e2f48-b2e2-4f26-9c4f-f266a45e956b.png)
![Screenshot_ubuntu20 04_2023-04-21_02:49:36](https://user-images.githubusercontent.com/9466814/233503039-650d46df-e053-4410-ac03-e54ee8fecbac.png)

I initially made a mistake and took a screenshot after uninstalling the extension, but the results were the same as before. However, upon further investigation, I realized that the "Docker" extension was not installed in the editor. After installing it and repeating the tests, the results were still the same. I have attached screenshots of all the tests, including the one with the clean installation of the virtual machine from the official image.

![Screenshot_ubuntu20 04_2023-04-21_02:51:21](https://user-images.githubusercontent.com/9466814/233503254-7a58a46a-c4be-466a-a4a7-8fd9a6b208f8.png)
![Screenshot_ubuntu20 04_2023-04-21_02:51:34](https://user-images.githubusercontent.com/9466814/233503260-b30182fb-ee7b-4bdb-a591-9f0d1b769431.png)

![Screenshot_ubuntu20 04_2023-04-21_02:59:02](https://user-images.githubusercontent.com/9466814/233504121-b8afe623-3437-462e-bc0f-01efab848c81.png)

**Comment by tobiasalthoff** [comment] 2023-04-25 07:38
Hey @tebaly ,sorry for my late response. I've another idea. Please add the following setting to your vscode settings:

"editor.semanticHighlighting.enabled": true

This should work 🤞

**Comment by tebaly** [comment] 2023-04-28 12:15
Thank you for your response and suggestion. Adding the "editor.semanticHighlighting.enabled": true setting to my Visual Studio Code settings did solve the issue with the Atom Material Theme extension.

However, I noticed that the default value for this setting was "configuredByTheme". Is it possible for the developer to make changes to the theme so that users don't have to change their editor settings manually?

Thank you for your help in resolving this issue.

**Comment by tobiasalthoff** [comment] 2023-04-30 10:14
I am glad that the problem is solved. I can set the semenaticHighlighted setting in the theme, but I decided against it at that time. I don't know why anymore, but there was a reason. I'll check again and close this issue for now, since the problem is solved.

**Closed as completed by tobiasalthoff** 2023-04-30 10:14 UTC
